{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  labels:
    app: {{ .Values.labels.app | default .Values.name }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}

