apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.labels.app | default .Values.name }}
spec:
  clusterIP: {{ .Values.clusterIP | default "ClusterIP" }}
  selector:
    app: {{ .Values.labels.app | default .Values.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
