{{- if eq .Values.kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.labels.app | default .Values.name }}
spec:
  serviceName: {{ .Values.serviceName | default .Values.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app | default .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app | default .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        {{- if .Values.secret }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: {{ .Values.secret.key | default "MYSQL_ROOT_PASSWORD" }}
        {{- end }}
        {{- if .Values.config }}
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.name }}
              key: {{ .Values.config.key | default "MYSQL_DATABASE" }}
        {{- end }}
        volumeMounts:
        - name: {{ .Values.persistence.name | default "mysql-data" }}
          mountPath: {{ .Values.persistence.mountPath | default "/var/lib/mysql" }}
        livenessProbe:
          exec:
            command: {{- toYaml .Values.livenessProbe.exec | nindent 12 }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
        readinessProbe:
          exec:
            command: {{- toYaml .Values.readinessProbe.exec | nindent 12 }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}

  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.persistence.name | default "mysql-data" }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.persistence.size | default "5Gi" }}
{{- end }}
